defmodule ProtocolTest do
  use ExUnit.Case

  test "to_simple_error with empty string" do
    assert_raise ArgumentError, fn -> Redis.Protocol.to_simple_error("") end
  end

  test "to_simple_error with non-empty string" do
    assert Redis.Protocol.to_simple_error("foo") == "-foo\r\n"
  end

  test "to_simple_string with empty string" do
    assert_raise ArgumentError, fn -> Redis.Protocol.to_simple_string("") end
  end

  test "to_simple_string with non-empty string" do
    assert Redis.Protocol.to_simple_string("foo") == "+foo\r\n"
  end

  test "to_bulk_string with empty string" do
    assert Redis.Protocol.to_bulk_string("") == "$0\r\n\r\n"
  end

  test "to_bulk_string with non-empty string" do
    assert Redis.Protocol.to_bulk_string("foo") == "$3\r\nfoo\r\n"
  end

  test "to_bulk_string_array with empty list" do
    assert Redis.Protocol.to_bulk_string_array([]) == "*0\r\n"
  end

  test "to_bulk_string_array with single value" do
    assert Redis.Protocol.to_bulk_string_array(["foo"]) == "*1\r\n$3\r\nfoo\r\n"
  end

  test "to_bulk_string_array with multiple values" do
    assert Redis.Protocol.to_bulk_string_array(["foo", "lorem"]) ==
             "*2\r\n$3\r\nfoo\r\n$5\r\nlorem\r\n"
  end

  test "to_bulk_string_array with nested arrays of bulk strings" do
    assert Redis.Protocol.to_bulk_string_array([["foo", "bar"], ["baz"]]) ==
             "*2\r\n*2\r\n$3\r\nfoo\r\n$3\r\nbar\r\n*1\r\n$3\r\nbaz\r\n"
  end

  test "explicit_stream_id valid id without previous id" do
    assert Redis.Protocol.explicit_stream_id("0-1") == {:ok, "0-1"}
    assert Redis.Protocol.explicit_stream_id("1-1") == {:ok, "1-1"}
    assert Redis.Protocol.explicit_stream_id("1-0") == {:ok, "1-0"}
  end

  test "explicit_stream_id invalid id without previous id" do
    assert Redis.Protocol.explicit_stream_id("0-0") == {:invalid, nil}
  end

  test "explicit_stream_id valid id with older previous id" do
    assert Redis.Protocol.explicit_stream_id("1-2", "1-1") == {:ok, "1-2"}
    assert Redis.Protocol.explicit_stream_id("2-1", "1-1") == {:ok, "2-1"}
    assert Redis.Protocol.explicit_stream_id("2-2", "1-2") == {:ok, "2-2"}
  end

  test "explicit_stream_id valid id with newer previous id" do
    assert Redis.Protocol.explicit_stream_id("1-1", "1-1") == {:too_small, nil}
    assert Redis.Protocol.explicit_stream_id("1-2", "1-2") == {:too_small, nil}
    assert Redis.Protocol.explicit_stream_id("2-1", "2-1") == {:too_small, nil}
    assert Redis.Protocol.explicit_stream_id("1-1", "2-2") == {:too_small, nil}
  end

  test "autogenerated_stream_seq" do
    assert Redis.Protocol.autogenerated_stream_seq("0-*") == {:ok, "0-1"}
    assert Redis.Protocol.autogenerated_stream_seq("1-*") == {:ok, "1-0"}
    assert Redis.Protocol.autogenerated_stream_seq("0-*", "0-2") == {:ok, "0-3"}
    assert Redis.Protocol.autogenerated_stream_seq("1-*", "1-0") == {:ok, "1-1"}
    assert Redis.Protocol.autogenerated_stream_seq("1-*", "1-2") == {:ok, "1-3"}
    assert Redis.Protocol.autogenerated_stream_seq("2-*", "1-2") == {:ok, "2-0"}
    assert Redis.Protocol.autogenerated_stream_seq("1-*", "2-2") == {:too_small, nil}
  end
end
